baseURL: http://localhost:1313/
title: TooGz.fr
paginate: 10
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: false

menu:
    main:
        - name: Posts
          url: posts/
          weight: 1
        - name: Archives
          url: archives/
          weight: 5
        - name: Tags
          url: tags
          weight: 10
        - name: Categories
          url: categories/
          weight: 10
        - name: Series
          url: series/
          weight: 10
    
outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    profileMode:
        enabled: true
        title: TooGz # optional
        subtitle: Mon petit bordel sur le web ...
        imageUrl: /img/TooGz.webp # optional
        imageTitle: TooGz aka Guillaume Boivin # optional
        imageWidth: 150 
        imageHeight: 150
        buttons:
          - name: Posts
            url: /posts
          - name: Réalisations
            url: /realisations
          - name: Rénovation
            url: /renovation
          - name: Autosuffisance
            url: /autosuffisance
          - name: Jardin
            url: /jardin

    socialIcons: # optional
      - name: "instagram"
        url: "https://www.instagram.com/toogz/"
      # - name: "Linkedin"
      #   url: "https://www.linkedin.com/in/guillaume-boivin-5118a93a/"
      # - name: Youtube
      #   url: https://www.youtube.com/channel/UCxN3Q5xyApglWp-COuydjxw

    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Le site web de la boivin Family"
    author: TooGz
    # author: ["Me", "You"] # multiple authors

    defaultTheme: dark #dark|light|auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowToc: false
    # comments: false
    images: ["papermod-cover.png"]


    homeInfoParams:
        Title: "PaperMod"
        Content: >
            Welcome to demo of hugo's theme PaperMod.

            - **PaperMod** is a simple but fast and responsive theme with useful feature-set that enhances UX.

            - Do give a 🌟 on Github !

            - PaperMod is based on theme [Paper](https://github.com/nanxiaobei/hugo-paper).

    # editPost:
    #     URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
    #     Text: "Suggest Changes" # edit text
    #     appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    # assets:
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: false # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true

module:
  imports:
  - path: github.com/hugomods/icons/vendors/bootstrap
  - path: github.com/hugomods/icons/vendors/font-awesome
